/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/pdfView copy.vue')['default']
    Directory: typeof import('./src/components/pdfDirectory/Directory.vue')['default']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Info: typeof import('./src/components/pdfDirectory/Info.vue')['default']
    PdfDirectory: typeof import('./src/components/PdfDirectory.vue')['default']
    PdfView: typeof import('./src/components/PdfView.vue')['default']
    PdfViewA1: typeof import('./src/components/PdfView-a1.vue')['default']
    Test1: typeof import('./src/components/Test1.vue')['default']
  }
}
